"""empty message

Revision ID: 681722d503d6
Revises: 
Create Date: 2023-10-21 10:37:18.530588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681722d503d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('whiskey',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('distillery', sa.String(length=200), nullable=True),
    sa.Column('bottler', sa.String(length=200), nullable=True),
    sa.Column('bottling_series', sa.String(length=200), nullable=True),
    sa.Column('year_bottled', sa.String(length=200), nullable=True),
    sa.Column('strength', sa.String(length=200), nullable=True),
    sa.Column('size', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whiskey')
    op.drop_table('user')
    # ### end Alembic commands ###
